// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6yaw-CJDtb4rt-LiRrc6OTXsWo2wiDq8',
    appId: '1:546203993278:web:7300525a2845ed907a4aef',
    messagingSenderId: '546203993278',
    projectId: 'healthbuddy-1fc61',
    authDomain: 'healthbuddy-1fc61.firebaseapp.com',
    storageBucket: 'healthbuddy-1fc61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_AYYGFSqfQbRWaKmKh6xOHsm835tOPA',
    appId: '1:546203993278:android:66c1c4a3fca77b917a4aef',
    messagingSenderId: '546203993278',
    projectId: 'healthbuddy-1fc61',
    storageBucket: 'healthbuddy-1fc61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOT_aW_WDDlj-fzO96qVPjD3D5fAFF_-g',
    appId: '1:546203993278:ios:40607913b40886d47a4aef',
    messagingSenderId: '546203993278',
    projectId: 'healthbuddy-1fc61',
    storageBucket: 'healthbuddy-1fc61.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOT_aW_WDDlj-fzO96qVPjD3D5fAFF_-g',
    appId: '1:546203993278:ios:40607913b40886d47a4aef',
    messagingSenderId: '546203993278',
    projectId: 'healthbuddy-1fc61',
    storageBucket: 'healthbuddy-1fc61.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6yaw-CJDtb4rt-LiRrc6OTXsWo2wiDq8',
    appId: '1:546203993278:web:d83090e6d8fb6a207a4aef',
    messagingSenderId: '546203993278',
    projectId: 'healthbuddy-1fc61',
    authDomain: 'healthbuddy-1fc61.firebaseapp.com',
    storageBucket: 'healthbuddy-1fc61.firebasestorage.app',
  );
}
